name: Coveralls

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Usar Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar dependencias
        run: npm ci
        working-directory: theory-examples

      - name: Ejecutar coverage
        run: npm run coverage
        working-directory: theory-examples

      - name: Enviar datos a Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: theory-examples/coverage/lcov.info